MIBI-add acquisition instrument vendor/model
hubmapconsortium/ingest-validation-tools pull request #1027
Opened 2022-01-20 16:58 UTC by cebriggs7135

Added acquisition instrument vendor and model to the level 2 metadata for MIBI schema.

2022-01-20 21:51 UTC, mccalluc requested changes
- Please remove defaults
- Will wait for confirmation from Nils that this is ok to modify in place

2022-01-20 21:51 UTC, mccalluc commented on src/ingest_validation_tools/table-schemas/assays/mibi-v1.yaml
> +    sequence_limit: 3
```suggestion
```
Defaults do not need to be given

2022-01-20 21:51 UTC, mccalluc commented on src/ingest_validation_tools/table-schemas/assays/mibi-v1.yaml
> +    sequence_limit: 3
```suggestion
```

2022-01-20 22:14 UTC, ngehlenborg approved these changes
I approve assuming  "modify in place" = "modify without bumping the version"

2022-01-21 19:57 UTC, mccalluc commented
I generate the docs here. Thanks.

2022-01-24 19:58 UTC, mccalluc commented
@cebriggs7135 -- Could you check the placement of these fields in the list? I believe that for other assays they are at the top of the "Unique to this type" list... but that's not the case here. Should they be?

2022-01-24 20:01 UTC, cebriggs7135 commented
@mccalluc You are correct. Acquisition instrument fields should be at the top of the "Unique to this type" list.

2022-01-24 20:52 UTC, mccalluc commented
@cebriggs7135 -- Ok, good to know: They were misplaced at the start of this PR. If you can review the output now and confirm that the field order is what you want, I'd appreciate it. Will wait to merge until I get your confirmation.

2022-01-25 19:50 UTC, cebriggs7135 reviewed
looks correct. thanks.

2022-01-25 20:09 UTC, mccalluc commented
Converting back to draft. This is not ready to go. The changes in https://github.com/hubmapconsortium/ingest-validation-tools/pull/1034 should be merged into this.

2022-01-25 22:32 UTC, mccalluc commented
Close in favor of #1035

2022-01-25 22:32 UTC, closed without merging