Free text slot
hubmapconsortium/ingest-validation-tools pull request #513
Opened 2021-01-25 19:04 UTC by mccalluc

@cebriggs7135 : Look at [codex](https://github.com/hubmapconsortium/ingest-validation-tools/blob/40c99b8742702306cdd69e71d6402936f0e1cec1/docs/codex/README.md) ... Is that a good place to insert a note, or would you prefer it somewhere else?

@cebriggs7135 + @ilan-gold : What precisely can say about the antibody IDs in this case? What does a future developer need to know about how the ID in the antibodies TSV relates to the contents of the files?

2021-01-25 19:24 UTC, ilan-gold commented
I think using https://www.antibodyregistry.org/ was mentioned but I am not 100% sure.  Still feel like I have blinders on with all this a bit...

2021-01-25 22:49 UTC, mccalluc commented
@ilan-gold -- see slack. I'm hoping you can take the lead in asking the questions that will clarify things. (I recognize that the task is really ill-defined!)

2021-01-27 20:33 UTC, mccalluc commented
(Will learn more Friday.)

2021-01-27 20:38 UTC, cebriggs7135 commented
@mccalluc @ilan-gold We know from Marda that the "cycle#_CH#" IDs in the channel_id column are generated exactly as you see them in that specific format by the Akoya instrument used for CODEX. I think I should find out what a channel_id would be for Lightsheet or MixIF or any other antibody-based assay. Then we can create more informed instructions for users in the README for each of those assays.

2021-01-28 17:08 UTC, mccalluc commented
Ilan says there will be discussion about this tomorrow. Hope to set direction after that. 

>  I think I should find out what a channel_id would be for Lightsheet or MixIF or any other antibody-based assay. Then we can create more informed instructions for users in the README for each of those assays.

That will be useful, but in this thread let's keep a focus on filling in the gaps for just this assay. Perhaps file issues for those others, if that helps? but may not be needed.

2021-02-01 14:45 UTC, cebriggs7135 commented
@chuck I put assay specific channel_id into the description in the antibodies TSV bit I didn't see it show as a PR so not sure what I did wrong.

2021-02-02 15:30 UTC, mccalluc commented
@ilan-gold : Per our discussion yesterday, you'll see this through to completion? Thanks!

2021-02-02 16:00 UTC, ilan-gold commented
@mccalluc The channel ID's are basically a free text for unique identifiers.  Cytokit uses them one way (to link up to file/folder names) but I don't think there is really a catch-all for saying what they are.  For example, with assays that have fewer processing requirements, they probably are not even necessary.  I will update this PR

2021-02-02 20:03 UTC, ilan-gold commented
@mccalluc @cebriggs7135 Does this README.md for [codex](https://github.com/hubmapconsortium/ingest-validation-tools/blob/e010de5d644737aeaae88b2721e6153db9bda001/docs/codex/README.md) now look right?

2021-02-04 21:41 UTC, mccalluc commented
Thanks, @ilan-gold : 
- I'll trim off the last section about `antibody_name`,  `rr_id`, and `uniprot_id`, since what's being said will be the same for every assay type.
- I'll change the paths to globs, to make it more readable.
- and I'll see if the md generation can avoid adding lines.

2021-02-08 16:29 UTC, cebriggs7135 commented
@mccalluc Going back to your original question at the top: 
 "Look at codex ... Is that a good place to insert a note, or would you prefer it somewhere else?"

I followed the link to the CODEX specs in Github but I do not see where you suggest the free text section would go. Can you help me understand better what you are asking?

2021-02-08 16:37 UTC, mccalluc commented
@cebriggs7135 
> I followed the link to the CODEX specs in Github but I do not see where you suggest the free text section would go. Can you help me understand better what you are asking?

Click on "Files changed", then go down to the go down to the readme, and click to render the markdown

https://github.com/hubmapconsortium/ingest-validation-tools/pull/513/files?short_path=ecb8358#diff-ecb8358eda22eb745f4db1748bbfe7ee7c646e9a2fc28aaec170cbf256ee7940

Is that a good place in the document to add this section, or would you prefer to see it elsewhere?

2021-02-08 16:53 UTC, cebriggs7135 requested changes

2021-02-08 16:53 UTC, cebriggs7135 commented on src/ingest_validation_tools/table-schemas/level-2/codex.yaml
> +  while each tif file on globus contains a single channel,
```suggestion
  while each tif file on Globus contains a single channel,
```

2021-02-09 14:48 UTC, merged