sample date -> sample datetime
hubmapconsortium/ingest-validation-tools pull request #520
Opened 2021-01-28 22:14 UTC by mccalluc

Fix #507; Fix #479?

If this is approved, I can then regenerate the docs, but I have several concerns:

- The request from Chris is straightforward, but it raises the bar on what we're expecting from the TMCs. Is there buy-in from every data provider?
- There was a concern expressed in the note that date alone could make the individual identifiable. Adding time would compound this. If this is approved, then I'd take it that issue (#479) is no longer a concern?
- "date" != "datetime" ... I would prefer to see this field renamed, if this goes forward.

2021-01-28 22:18 UTC, ngehlenborg commented
Can we add this to the agenda for our next meeting? I don't have enough context to comment.

2021-01-28 22:38 UTC, mccalluc commented
done.

2021-02-03 15:04 UTC, cebriggs7135 commented
I'll ask Gloria P and Shin Lin, & TMCs re: capturing date time -sample acquisition re: pt id. TMCs have this info & how much effort?

2021-02-08 17:00 UTC, ngehlenborg commented
@mccalluc This will need to wait until we have input from HuBMAP with regard to 

1. patient identification concerns and 
2. availability of the requested information at the TMCs (we will not introduce this if it is rarely collected or available)

2021-02-09 23:44 UTC, cebriggs7135 requested changes
This should not be implemented based on comments from TMCs. Time of procedure is not informative about circadian rhythm effects.

2021-02-11 22:16 UTC, closed without merging