Flag fields which have been auto-incremented by Excel
hubmapconsortium/ingest-validation-tools pull request #568
Opened 2021-02-23 21:00 UTC by mccalluc

Fix #540 

Schemas can specify the length of sequence of incrementing integers which will be flagged as an error, because it's probably coming from Excel. This is different from the other validations because it is at the core a heuristic, so the limit should be set conservatively, since we don't have a distinction between non-fatal warnings, and fatal errors.

This could be exposed in the generated documentation, but I don't think that's necessary: This doesn't change anything about the *meaning* of the fields.

@cebriggs7135 -- I think it will be your responsibility to decide what the limit should be, where it should be applied.

(Not sure why mypy was scanning this file: I'm not interested in diving into those annotations right now and I just want to silence the error.)

2021-02-24 17:08 UTC, cebriggs7135 requested changes
The cutoff should be the first instance of an increment of 1. Any increment should be flagged for review but not necessarily as an error that must be changed - in case it's correct.

2021-02-24 19:43 UTC, mccalluc commented
@cebriggs7135 -- We have no machinery for warnings which are not errors.... and I'm reluctant to add it: We would need a way to configure warnings separately from errors, and we would need a way to report them separately. These are the ways I see forward:
- Merge this, but use high limits, so that only situations which are definitely errors will be flagged.
- Merge this, and configure it to error after runs of only 2: The TMC will be responsible for reordering the rows to avoid sequences.
- Wait until "warnings" are handled separately from "errors". (This will not come for a long time.)

2021-02-26 17:10 UTC, cebriggs7135 approved these changes

2021-02-27 02:31 UTC, jswelling approved these changes
I concur that we can flag it as an error after a run of only 2, because re-ordering the lines is always an option.  Well, I can think of a really convoluted example where reordering won't work, but the option of splitting the .tsv file would still exist.

2021-02-27 21:56 UTC, merged