Lightsheet directory schema
hubmapconsortium/ingest-validation-tools pull request #653
Opened 2021-03-24 19:22 UTC by icaoberg

First version of the Lightsheet directory schema.

Test: this schema was used to validate a dataset from UFL.

2021-03-24 20:37 UTC, mccalluc requested changes
Check the regex syntax. I remain concerned when there are CSVs and we don't say what the columns are. Tests need to pass before merge, and ideally before review is requested.

... but zooming out, I think I'm only on this PR because I'm a codeowner? Is the right course for me to remove myself, so I won't be auto-assigned in the future?

2021-03-24 20:37 UTC, mccalluc commented on src/ingest_validation_tools/directory-schemas/lightsheet.yaml
> +  pattern: 'Level0/Channel+[^/]/[^/]+\.csv'
```suggestion
  pattern: 'Level0/Channel[^/]+/[^/]+\.csv'
```

What you have allows the `l` to be repeated.

2021-03-25 00:54 UTC, icaoberg commented
> Check the regex syntax. I remain concerned when there are CSVs and we don't say what the columns are. Tests need to pass before merge, and ideally before review is requested.
> 
> ... but zooming out, I think I'm only on this PR because I'm a codeowner? Is the right course for me to remove myself, so I won't be auto-assigned in the future?

Agree. I was able to get some information from University of Florida. I can certainly ask them to revise the description.

2021-05-17 21:46 UTC, jswelling approved these changes

2021-05-17 21:48 UTC, jswelling commented
@icaoberg I've reviewed and approved, but I'm not sure who is supposed to actually resolve the conflicted files and do the merge.  @mccalluc does it fall to @icaoberg to carry out the actual merge?

2021-05-17 21:51 UTC, mccalluc commented
Yes, @icaoberg can get tests to pass and then merge.

2021-06-07 18:59 UTC, jswelling reviewed
So basically the only thing required is the unstitched ome.tiff?  Are there combinations of not-required files that we expect to see together? I know we don't have a way to enforce this now, but only requiring the one file seems pretty sparse.
Also, do we need to validate the integrity of the .czi file?

2021-06-07 19:16 UTC, icaoberg commented
> So basically the only thing required is the unstitched ome.tiff? Are there combinations of not-required files that we expect to see together? I know we don't have a way to enforce this now, but only requiring the one file seems pretty sparse.
> Also, do we need to validate the integrity of the .czi file?

@jswelling to the best of my knowledge this is correct. Hunter from Florida already did a preliminary local validation. 

I am not aware if we need to validate the czi, . Most DP are providing the .czi because this is the output file from their microscopes/devices.

2021-06-07 19:55 UTC, merged