factor out sc_isolation_enrichment
hubmapconsortium/ingest-validation-tools pull request #824
Opened 2021-05-19 17:35 UTC by mccalluc

Use the suggest-edit mechanism to indicate which is the correct definition for this field; Chuck will followup and regenerate docs.

2021-05-26 14:30 UTC, cebriggs7135 requested changes
Give HCA the same enums for this field.

2021-05-26 14:30 UTC, cebriggs7135 commented on src/ingest_validation_tools/table-schemas/includes/fields/sc_isolation_enrichment.yaml
> +    required: true
```suggestion
       enum:
           - none
           - FACS
```

2021-05-26 14:30 UTC, cebriggs7135 commented on src/ingest_validation_tools/table-schemas/includes/fields/sc_isolation_enrichment.yaml
> +    required: true
This should have the same enums as the other sc assays.

2021-06-08 21:28 UTC, mccalluc commented on src/ingest_validation_tools/table-schemas/includes/fields/sc_isolation_enrichment.yaml
> +    required: False
```suggestion
```

2021-06-08 21:28 UTC, mccalluc commented on src/ingest_validation_tools/table-schemas/includes/fields/sc_isolation_enrichment.yaml
> +# scatacseq-v0.yaml; scatacseq-v1.yaml; scrnaseq-v1.yaml; scrnaseq-v2.yaml
```suggestion
```

2021-06-29 15:47 UTC, closed without merging