factor out sc_isolation_entity
hubmapconsortium/ingest-validation-tools pull request #825
Opened 2021-05-19 17:35 UTC by mccalluc

Use the suggest-edit mechanism to indicate which is the correct definition for this field; Chuck will followup and regenerate docs.

2021-05-26 14:26 UTC, cebriggs7135 requested changes
Make the same enums for this field in HCA schema as for the other sc schema.

2021-05-26 14:26 UTC, cebriggs7135 commented on src/ingest_validation_tools/table-schemas/includes/fields/sc_isolation_entity.yaml
> +  description: The type of single cell entity derived from isolation protocol
```suggestion
  description: The type of single cell entity derived from isolation protocol
  constraints:
     enum:
         - whole cell
         - nucleus
         - cell-cell multimer
         - spatially encoded cell barcoding
```

2021-05-26 14:26 UTC, cebriggs7135 commented on src/ingest_validation_tools/table-schemas/includes/fields/sc_isolation_entity.yaml
> +    required: true
```suggestion
```

2021-05-26 14:26 UTC, cebriggs7135 commented on src/ingest_validation_tools/table-schemas/includes/fields/sc_isolation_entity.yaml
> +  description: The type of single cell entity derived from isolation protocol
Add the same enums to this field for HCA as for the other sc/sn seq schema.

2021-06-08 21:22 UTC, mccalluc commented on src/ingest_validation_tools/table-schemas/includes/fields/sc_isolation_entity.yaml
> +# scrnaseq-hca-v0.yaml
```suggestion
```

2021-06-08 21:23 UTC, mccalluc commented on src/ingest_validation_tools/table-schemas/includes/fields/sc_isolation_entity.yaml
> +      - spatially encoded cell barcoding
```suggestion
```

2021-06-29 15:52 UTC, merged