Mccalluc/czems tweaks
hubmapconsortium/ingest-validation-tools pull request #861
Opened 2021-05-31 19:40 UTC by mccalluc

Extend #859 
Fix #857

Please resolve the TODOs.

2021-06-04 15:30 UTC, cebriggs7135 requested changes
I think we need to have a new assay_category called mass spectrometry and GC-MS and CE-MS will be assay_types of mass_spectrometry.
I'll likely have more edits in the definitions.

2021-06-08 19:17 UTC, mccalluc commented on docs/czems/czems-metadata.tsv
> +1										mass_spectrometry_imaging	CZE-MS	protein / metabolites / lipids / peptides / phosphopeptides / glycans				ESI / MALDI / DESI	negative ion mode / positive ion mode					TIMS / TWIMS / FAIMS
Remember to update src, not TSV.

2021-06-08 19:18 UTC, mccalluc commented
@cebriggs7135 -- Lots of TODOs in the schema need to be addressed.

2021-06-14 15:23 UTC, mccalluc commented
@cebriggs7135 -- As discussed, I will merge this to the parent branch, and you can confirm that the over-all list of fields is correct, and and the descriptions can be handled later.

2021-06-14 15:24 UTC, merged