cell_barcode fields are not required for sciATACseq
hubmapconsortium/ingest-validation-tools pull request #876
Opened 2021-06-14 19:50 UTC by cebriggs7135

cell_barcode fields are not required for sciATACseq or SNAREseq either (as was already noted in parentheses)
Added required: FALSE for cell_barcode read, index & size

2021-06-15 21:04 UTC, mccalluc requested changes
`required` must be indented under `constraints`. Please correct all three.

2021-06-15 21:04 UTC, mccalluc commented on src/ingest_validation_tools/table-schemas/assays/scatacseq-v1.yaml
> +  required: FALSE
```suggestion
  constraints:
    required: False
```

2021-06-15 23:26 UTC, cebriggs7135 commented on src/ingest_validation_tools/table-schemas/assays/scatacseq-v1.yaml
> +  required: FALSE
```suggestion
  constraints:
    required: FALSE
```

2021-06-15 23:26 UTC, cebriggs7135 commented on src/ingest_validation_tools/table-schemas/assays/scatacseq-v1.yaml
> +  required: FALSE
```suggestion
  constraints
    required: FALSE
```

2021-06-17 14:06 UTC, cebriggs7135 reviewed
Made the requested edits putting ```constraints:``` above ```required: FALSE```. This is ready for merging.

2021-06-17 14:57 UTC, mccalluc commented
Failed on 
```
> antibodies TSV errors:
> - 'On row 2, column "uniprot_accession_number", value "G9N9I7" fails because URL returned
>   HTTPSConnectionPool(host=''www.uniprot.org'', port=443): Max retries exceeded with
>   url: /uniprot/G9N9I7 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
>   object at 0x7f720a7a3dd8>: Failed to establish a new connection: [Errno -2] Name
>   or service not known'',)): "https://www.uniprot.org/uniprot/G9N9I7"'
```
Will try re-running... May be sporadic network problem.

2021-06-17 15:05 UTC, merged