Make provision to provide kwargs to validation plug-ins.
hubmapconsortium/ingest-validation-tools pull request #888
Opened 2021-06-22 01:54 UTC by jswelling

Some new plugin validation tests will need access to the auth token, and the most efficient way to provide it is to allow Airflow to pass it down to the the plugins via kwargs.  This PR adds the necessary kwargs arguments to do so.

2021-06-22 17:02 UTC, mccalluc requested changes
tweaks?

2021-06-22 17:02 UTC, mccalluc commented on src/ingest_validation_tools/upload.py
> +        plugin_errors = self._get_plugin_errors(**kwargs)
```suggestion
        plugin_errors = self._get_plugin_errors(**plugin_kwargs)
```

2021-06-23 21:18 UTC, jswelling commented on src/ingest_validation_tools/upload.py
> +    def get_errors(self, **kwargs):
No objection, assuming you don't mind passing two instances of the auth token if you need it.

2021-06-23 22:20 UTC, mccalluc approved these changes
Merge at your convenience.

2021-06-24 00:57 UTC, merged