update scrnaseq cell_barcode_read description: comma-delimited list
hubmapconsortium/ingest-validation-tools pull request #941
Opened 2021-08-26 15:47 UTC by cebriggs7135

In cases where more than one read file is involved, enter a comma-delimited list of the filenames in this field.

2021-08-30 15:40 UTC, ngehlenborg requested changes

2021-08-30 15:40 UTC, ngehlenborg commented on src/ingest_validation_tools/table-schemas/assays/scrnaseq-v2.yaml
> +  description: Which read file(s)contains the cell barcode. Multiple cell_barcode_read files must be provided as a comma-delimited list (e.g. file1,file2,file3).
```suggestion
  description: Which read file(s) contains the cell barcode. Multiple cell_barcode_read files must be provided as a comma-delimited list (e.g. file1,file2,file3).
```

2021-08-30 21:14 UTC, cebriggs7135 reviewed
done

2021-09-01 19:48 UTC, mccalluc commented
@cebriggs7135 : Currently failing with
```
<   description: Which read file contains the cell barcode
---
>   description: Which read file(s) contains the cell barcode. Multiple cell_barcode_read
>     files must be provided as a comma-delimited list (e.g. file1,file2,file3).
Update needed: src/generate_docs.py scrnaseq docs/scrnaseq
```

2021-09-02 21:32 UTC, merged