level 1 metadata update
hubmapconsortium/ingest-validation-tools pull request #960
Opened 2021-10-01 20:52 UTC by cebriggs7135

Changed "3" to "4" assay_categories and added imaging_mass_spectrometry to the list.

2021-10-01 21:49 UTC, mccalluc requested changes
regenerate docs, and add a changelog.

2021-10-03 23:09 UTC, cebriggs7135 reviewed
Does this mean you made the same edits to the schema_loaded.py file?

2021-10-04 14:05 UTC, mccalluc commented
@cebriggs7135 -- Sorry for the ambiguity: I meant that you need to regenerate docs, and add a changelog entry in this branch. Then tests will pass, and this can be merged.

2021-10-05 16:11 UTC, mccalluc approved these changes

2021-10-05 16:11 UTC, merged