LCMS Hotfix
hubmapconsortium/ingest-validation-tools pull request #989
Opened 2021-11-12 03:18 UTC by icaoberg

This fix addresses the regex issue posted by @mccalluc 

This fix for the `raw_data` folder regex should now match the example provided by the TMC

```
raw_data/20200707_rmi049_75umPLRPS_Kidney_GF10pc_VAN0003LK32_biorep01_techrep01.raw
raw_data/20200707_rmi049_75umPLRPS_Kidney_GF10pc_VAN0003LK32_biorep01_techrep02.raw
raw_data/20200707_rmi049_75umPLRPS_Kidney_GF10pc_VAN0003LK32_biorep02_techrep01.raw
raw_data/20200707_rmi049_75umPLRPS_Kidney_GF10pc_VAN0003LK32_biorep02_techrep02.raw
raw_data/20200707_rmi049_75umPLRPS_Kidney_GF10pc_VAN0003LK32_biorep03_techrep01.raw
raw_data/20200707_rmi049_75umPLRPS_Kidney_GF10pc_VAN0003LK32_biorep03_techrep02.raw
raw_data/20200707_rmi049_75umPLRPS_Kidney_GF10pc_VAN0003LK32_biorep04_techrep01.raw
raw_data/20200707_rmi049_75umPLRPS_Kidney_GF10pc_VAN0003LK32_biorep04_techrep02.raw
raw_data/20200707_rmi049_75umPLRPS_Kidney_GF10pc_VAN0003LK32_biorep05_techrep01.raw
raw_data/20200707_rmi049_75umPLRPS_Kidney_GF10pc_VAN0003LK32_biorep05_techrep02.raw
```

2021-11-12 17:02 UTC, jswelling approved these changes

2021-11-12 17:55 UTC, icaoberg commented
@mccalluc the checks keep failing but I cannot recreate these errors locally and are related to running running the examples, not the changes I have made to the schema or documentation. Please advice how to proceed.

2021-11-12 20:20 UTC, icaoberg commented
@mccalluc I looked at your GitHub Action
* I am running Ubuntu 20.04 while the Action builds on 18.04
* I am running Python 3.7 while the Action runs Python 3.6

From a comment in your action it needs to be this combination of Ubuntu+Python but I cannot recreate this error locally.

2021-11-15 15:08 UTC, mccalluc requested changes
`.` in regex means any character. If you want a literal period, please escape.

2021-11-15 15:08 UTC, mccalluc commented on src/ingest_validation_tools/directory-schemas/lcms.yaml
> +  pattern: 'raw_data/[^/]*.(raw|mzML)'
```suggestion
  pattern: 'raw_data/[^/]+\.(raw|mzML)'
```

2021-11-15 15:08 UTC, mccalluc commented on src/ingest_validation_tools/directory-schemas/lcms.yaml
> +  pattern: 'ID_search_results/[^/]*.(txt|csv)'
```suggestion
  pattern: 'ID_search_results/[^/]+\.(txt|csv)'
```

2021-11-15 15:08 UTC, mccalluc commented on src/ingest_validation_tools/directory-schemas/lcms.yaml
> +  pattern: 'ID_metadata/[^/]*.xml'
```suggestion
  pattern: 'ID_metadata/[^/]+\.xml'
```

2021-11-15 15:08 UTC, mccalluc commented on src/ingest_validation_tools/directory-schemas/lcms.yaml
> +  pattern: 'QC_results/[^/]*.(xml|txt|html|pdf|log|yaml)'
```suggestion
  pattern: 'QC_results/[^/]+\.(xml|txt|html|pdf|log|yaml)'
```

2021-11-15 15:34 UTC, icaoberg commented on src/ingest_validation_tools/directory-schemas/lcms.yaml
> +  pattern: 'QC_results/[^/]*.(xml|txt|html|pdf|log|yaml)'
@mccalluc thanks for the suggestion.

2021-11-15 16:30 UTC, jswelling approved these changes

2021-11-15 18:24 UTC, merged